dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
env:
  - SPHINX=">=1.3,<1.4"
  - SPHINX=">=1.4,<1.5"
  - SPHINX=">=1.5,<1.6"
  - SPHINX=">=1.6,<1.7"
  - SPHINX=">=1.7,<1.8"
install:
  - pip install -r dev-requirements.txt
  - pip install "sphinx$SPHINX"
script:
  # Primary test suite
  - inv test
  # Integration-level test suite (hard to reliably test full stack in-code :()
  - inv test -o --tests=integration
  # Docs sanity check
  - inv docs
